# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecadf61c405cecea5707b0c95836ac395d495ec51840c954a38432448fe8976a2e79ba5e676872b043eadee995f86eaed5f73cb245ab9c5b43150825b3fa04fe

test:
  secret_key_base: d2f12331f04a3c4f35d5e84362bc9f5ecf56501c441a5c7a69179147a438e2ac2492b78b87ed234348385de187b96ae97da8c59538cad974610be375e40ac58a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
