# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 963acd626abc06e409d5b6c24812985dbf4d3c907cfc6b3b6e94e4f7581f99b4a258b23e0964207128aaacaad2d120ccb23bfbc945134232b06c906063c19d1e

test:
  secret_key_base: de775c4b880f8ed34036bd79872eb867072e4e7d2ad1062eeeba920389ee249f39fae3d99849b694cfa68ce36229785bbdb5e42b1c00df1db6c6e359c2f64d19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
