# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5aa30b29dd0636574a4b2bbd1e632812d988f2c16d55529c52bb476b4a32af4aca6998e82add51db85bf5de8b463e1bc0fe4df2e497972e1e76945136b3d1fdd

test:
  secret_key_base: 8ab24242a566f3dd28653b91ee040ac4210330e5ff2119942c00cb4a59bd113e911d3d1d5e6a50a952094157095e8f952681b47d97aa6623f4f039d626be57fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
