# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcfa27ac1f4ccd38a38c281056a36ec1767c61f4fe7d1c983d26596d0127d862e31ecd135c75ce876ebe3b609e622fb221ef1998c0c9c2cc7a09799b982e4830

test:
  secret_key_base: 6730db4bb8aa3f237e6e8580fa5e2072a51ec824502f44a973a148d8505bbfd1b0441510eba789d6589f140e00f4ac20edf2678c9ac33ac9c3ff20311b4e5539

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
